### ISSUE TITLE
Status for started

### ISSUE THREAD

**Issue by timwsuqld** [healthchecks/dashboard#2]
If using healthchecks with "started" triggers as well, it may be useful to have another color for started jobs (status-started)

Thanks

**Comment by McBochi** [comment]
Should be pretty easy to do it yourself, you could add a simple class to your Stylesheet, i.e.:
```
.theme-dark #panel > div.status-started {
    color: #FFF;
    background-image: linear-gradient(135deg, #263026 41.67%, #ffffff 41.67%, #ffffff 50%, #263026 50%, #263026 91.67%, #ffffff 91.67%, #ffffff 100%);
    background-size: 12.00px 12.00px;
}
```
Source: http://stripesgenerator.com/

I assume the API is returning "started", but I currently have no such monitor set up.

**Comment by timwsuqld** [comment]
@McBochi I am aware of how to do it myself, but it would be nice to have it as part of the included index.html. 

The api does return a started status already. I have the following changes in my setup
```css
        .theme-dark #panel > div.status-started {
            color: #FFF;
            background: #FF5600;
        }
```

I also have a nice blinking alert for down if anyone is interested.
```css
        .theme-dark #panel > div.status-down {
            color: #000;
            background: #ff3929;
            animation: alert-animation 1s infinite;
        }

        @-webkit-keyframes alert-animation {
          0%, 49% {
            background-color: #ff3929;

          }
          50%, 100% {
            background-color: #FF9500;

          }
        }
```
